export const SUPABASE_URL = "https://lxoletavhzzxfjzgbdyh.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4b2xldGF2aHp6eGZqemdiZHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5MDQxMDUsImV4cCI6MjEwMTQ4MDEwNX0.T-QSb7_CyPYrwxOpDntSpXs07m0Nr-jpVofiqafVAuQ";
